In [1]:
import pandas as pd
import logging
import seaborn as sn
import matplotlib.pyplot as plt

In [2]:
#read validation dataset
val = pd.read_csv('dev.tsv', sep='\t')
val

,id,Tweet,Claim,Stance,Premise
0,7212131785749,Ordered a mask that had a cute chain attached ...,face masks,FAVOR,0
1,2367433035,Who is ready for some #baseball? #BaseballisB...,stay at home orders,NONE,0
2,496011,"@Mystere07623203 @va_shiva @Liberty13046 130,0...",face masks,FAVOR,1
3,1490686,When they ask me what I did with my life I wil...,face masks,FAVOR,0
4,1209366,Taylor not putting her album in physical store...,stay at home orders,FAVOR,0
...,...,...,...,...,...
595,2949472,@BrianKempGA is one of the few #Governors that...,face masks,AGAINST,1
596,208269,I tested positive for Covid. Got it from a fri...,face masks,FAVOR,1
597,2316008,"If you are under retirement age, you have a *m...",stay at home orders,AGAINST,1
598,659269,@TheLalasventure @doqholliday @realDonaldTrump...,face masks,FAVOR,0
599,1940282,@Caissie Obviously I was simply practicing my ...,face masks,FAVOR,0

In [3]:
#rename columns to match SimpleTransformers format
column_names = {'Tweet': 'text'}
val = val.rename(columns = column_names)

val

,id,text,Claim,Stance,Premise
0,7212131785749,Ordered a mask that had a cute chain attached ...,face masks,FAVOR,0
1,2367433035,Who is ready for some #baseball? #BaseballisB...,stay at home orders,NONE,0
2,496011,"@Mystere07623203 @va_shiva @Liberty13046 130,0...",face masks,FAVOR,1
3,1490686,When they ask me what I did with my life I wil...,face masks,FAVOR,0
4,1209366,Taylor not putting her album in physical store...,stay at home orders,FAVOR,0
...,...,...,...,...,...
595,2949472,@BrianKempGA is one of the few #Governors that...,face masks,AGAINST,1
596,208269,I tested positive for Covid. Got it from a fri...,face masks,FAVOR,1
597,2316008,"If you are under retirement age, you have a *m...",stay at home orders,AGAINST,1
598,659269,@TheLalasventure @doqholliday @realDonaldTrump...,face masks,FAVOR,0
599,1940282,@Caissie Obviously I was simply practicing my ...,face masks,FAVOR,0

In [4]:
val = val.drop(columns=['Claim'])
val

,id,text,Stance,Premise
0,7212131785749,Ordered a mask that had a cute chain attached ...,FAVOR,0
1,2367433035,Who is ready for some #baseball? #BaseballisB...,NONE,0
2,496011,"@Mystere07623203 @va_shiva @Liberty13046 130,0...",FAVOR,1
3,1490686,When they ask me what I did with my life I wil...,FAVOR,0
4,1209366,Taylor not putting her album in physical store...,FAVOR,0
...,...,...,...,...
595,2949472,@BrianKempGA is one of the few #Governors that...,AGAINST,1
596,208269,I tested positive for Covid. Got it from a fri...,FAVOR,1
597,2316008,"If you are under retirement age, you have a *m...",AGAINST,1
598,659269,@TheLalasventure @doqholliday @realDonaldTrump...,FAVOR,0
599,1940282,@Caissie Obviously I was simply practicing my ...,FAVOR,0

In [5]:
val.to_csv('stance_predictions.tsv', sep='\t', index=False)

In [18]:
old_string = val.at[204, 'Claim']
print(old_string)

My new mask is sooo cute I don't wanna take it off even at home and the best part is its sustainable    face masks

In [19]:
val.at[204, 'Tweet'] = "My new mask is sooo cute I don't wanna take it off even at home and the best part is its sustainable"

In [20]:
val.at[204, 'Claim'] = "face masks"

In [21]:
display(val.iloc[204])

id                                                   3181898
Tweet      My new mask is sooo cute I don't wanna take it...
Claim                                             face masks
Stance                                                  NONE
Premise                                                    0
Name: 204, dtype: object

In [22]:
#save model predictions to .tsv file
val.to_csv('../dev.tsv', sep='\t', index=False)